<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE.'/lib/table_data_sql.class.php';
require_once NOALYSS_INCLUDE.'/class/database.class.php';

/**
 * class_action_gestion_comment_sql.php
 *
 * @file
 * @brief abstract of the table public.action_gestion_comment */
class Action_Gestion_Comment_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.action_gestion_comment";
        $this->primary_key="agc_id";
        /*
         * List of columns
         */
        $this->name=array(
            "agc_id"=>"agc_id"
            , "ag_id"=>"ag_id"
            , "agc_date"=>"agc_date"
            , "agc_comment"=>"agc_comment"
            , "tech_user"=>"tech_user"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "agc_id"=>"numeric"
            , "ag_id"=>"numeric"
            , "agc_date"=>"timestamp with time zone"
            , "agc_comment"=>"text"
            , "tech_user"=>"text"
        );


        $this->default=array(
            "agc_id"=>"auto",
            "agc_date"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
