<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * class_attr_def_sql.php
 *
 * @file
 * @brief abstract of the table public.attr_def */

/**
 * @class Attr_Def_SQL
 * @brief ORM of the table public.attr_def
 */
class Attr_Def_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.attr_def";
        $this->primary_key="ad_id";
        /*
         * List of columns
         */
        $this->name=array(
            "ad_id"=>"ad_id"
            , "ad_text"=>"ad_text"
            , "ad_type"=>"ad_type"
            , "ad_size"=>"ad_size"
            , "ad_extra"=>"ad_extra"
            , "ad_search_followup"=>"ad_search_followup"
            ,"ad_default_order"=>"ad_default_order"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "ad_id"=>"numeric"
            , "ad_text"=>"text"
            , "ad_type"=>"text"
            , "ad_size"=>"text"
            , "ad_extra"=>"text"
            , "ad_search_followup"=>"numeric"
            , "ad_default_order"=>"numeric"
        );


        $this->default=array(
            "ad_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
