<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
// Copyright (2002-2020) Author Dany De Bontridder <danydb@noalyss.eu>

require_once NOALYSS_INCLUDE.'/lib/noalyss_sql.class.php';
require_once NOALYSS_INCLUDE.'/class/database.class.php';

/**
 * class_contact_option_ref_sql.php
 *
 * @file
 * @brief abstract of the table public.contact_option_ref */
class Contact_option_ref_SQL extends Noalyss_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.contact_option_ref";
        $this->primary_key="cor_id";
        /*
         * List of columns
         */
        $this->name=array(
            "cor_id"=>"cor_id"
            , "cor_label"=>"cor_label"
            , "cor_type"=>"cor_type"
            , "cor_value_select"=>"cor_value_select"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "cor_id"=>"numeric"
            , "cor_label"=>"text"
            , "cor_type"=>"numeric"
            , "cor_value_select"=>"text"
        );


        $this->default=array(
            "cor_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
