<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * class_forecast_item_sql.php
 *
 * @file
 * @brief abstract of the table public.forecast_item
 */
/**
 * @class Forecast_Item_SQL
 * @brief ORM abstract of the table public.forecast_item
 */
class Forecast_Item_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.forecast_item";
        $this->primary_key="fi_id";
        /*
         * List of columns
         */
        $this->name=array(
            "fi_id"=>"fi_id"
            , "fi_text"=>"fi_text"
            , "fi_account"=>"fi_account"
            , "fi_order"=>"fi_order"
            , "fc_id"=>"fc_id"
            , "fi_amount"=>"fi_amount"
            , "fi_pid"=>"fi_pid"
            , "fi_amount_initial"=>"fi_amount_initial"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "fi_id"=>"numeric"
            , "fi_text"=>"text"
            , "fi_account"=>"text"
            , "fi_order"=>"numeric"
            , "fc_id"=>"numeric"
            , "fi_amount"=>"numeric"
            , "fi_pid"=>"numeric"
            , "fi_amount_initial"=>"numeric"
        );


        $this->default=array(
            "fi_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
