<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


/**
 * class_forecast_category_sql.php
 *
 * @file
 * @brief abstract of the table public.forecast_category
 */
class Forecast_Category_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id = -1)
    {
        $this->table = "public.forecast_category";
        $this->primary_key = "fc_id";
        /*
         * List of columns
         */
        $this->name = array(
            "fc_id" => "fc_id"
        , "fc_desc" => "fc_desc"
        , "f_id" => "f_id"
        , "fc_order" => "fc_order"
        );
        /*
         * Type of columns
         */
        $this->type = array(
            "fc_id" => "numeric"
        , "fc_desc" => "text"
        , "f_id" => "numeric"
        , "fc_order" => "numeric"
        );


        $this->default = array(
            "fc_id" => "auto"
        );

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }


}