<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * class_form_detail_sql.php
 *
 * @file
 * @brief abstract of the table public.form_detail */
 /**
 * @class Form_Detail_SQL
 * @brief ORM abstract of the table public.form_detail */
class Form_Detail_SQL extends \Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.form_detail";
        $this->primary_key="fo_id";
        /*
         * List of columns
         */
        $this->name=array(
            "fo_id"=>"fo_id"
            , "fo_fr_id"=>"fo_fr_id"
            , "fo_pos"=>"fo_pos"
            , "fo_label"=>"fo_label"
            , "fo_formula"=>"fo_formula"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "fo_id"=>"numeric"
            , "fo_fr_id"=>"numeric"
            , "fo_pos"=>"numeric"
            , "fo_label"=>"text"
            , "fo_formula"=>"text"
        );

        $this->default=array(
            "pk composé"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
