<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * jrn_tax_sql.class.php
 *
 * @file
 * @brief abstract of the table public.jrn_tax */

/**
 * @class Jrn_Tax_SQL
 * @brief ORM of the table public.jrn_tax
 */

class Jrn_Tax_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.jrn_tax";
        $this->primary_key="jt_id";
        /*
         * List of columns
         */
        $this->name=array(
            "jt_id"=>"jt_id"
        , "j_id"=>"j_id"
        , "pcm_val"=>"pcm_val"
        , "ac_id"=>"ac_id"
        );
        /*
         * Type of columns
         */
        $this->type=array(
             "jt_id"=>"number"
            , "j_id"=>"number"
            , "pcm_val"=>"text"
            , "ac_id"=>"ac_id"
        );


        $this->default=array(
            "jt_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}