<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE . '/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE . '/class/database.class.php';

/**
 * @file
 * @brief abstract of the table public.jrn_sup_document
 */

/**
 * @class Jrn_Sup_Document_SQL
 * @brief abstract of the table public.jrn_sup_document
 */
class Jrn_Sup_Document_SQL extends \Table_Data_SQL
{

    function __construct(Database $p_cn, $p_id = -1)
    {
        $this->table = "public.jrn_sup_document";
        $this->primary_key = "js_id";
        /*
         * List of columns
         */
        $this->name = array(
            "js_id" => "js_id"
            , "js_mimetype" => "js_mimetype"
            , "js_lob" => "js_lob"
            , "jr_id" => "jr_id"
            ,'js_filename'=>'js_filename'
            ,'js_description'=>'js_description'
            ,'js_cbc_id'=>'js_cbc_id'
        );

        /*
         * Type of columns
         */
        $this->type = array(
            "js_id" => "numeric"
            , "js_mimetype" => "text"
            , "js_lob" => "oid"
            , "jr_id" => "numeric"
            ,'js_filename'=>'text'
            ,'js_description'=>'text'
            ,'js_cbc_id'=>'text'
        );

        $this->default = array("js_id" => "auto");

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }
}
