<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE.'/lib/table_data_sql.class.php';
require_once NOALYSS_INCLUDE.'/class/database.class.php';

/**
 * class_jrn_def_sql.php
 *
 * @file
 * @brief abstract of the table public.jrn_def */
class Jrn_def_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.jrn_def";
        $this->primary_key="jrn_def_id";
        /*
         * List of columns
         */
        $this->name=array(
            "jrn_def_id"=>"jrn_def_id"
            , "jrn_def_name"=>"jrn_def_name"
            , "jrn_def_class_deb"=>"jrn_def_class_deb"
            , "jrn_def_class_cred"=>"jrn_def_class_cred"
            , "jrn_def_fiche_deb"=>"jrn_def_fiche_deb"
            , "jrn_def_fiche_cred"=>"jrn_def_fiche_cred"
            , "jrn_deb_max_line"=>"jrn_deb_max_line"
            , "jrn_cred_max_line"=>"jrn_cred_max_line"
            , "jrn_def_ech"=>"jrn_def_ech"
            , "jrn_def_ech_lib"=>"jrn_def_ech_lib"
            , "jrn_def_type"=>"jrn_def_type"
            , "jrn_def_code"=>"jrn_def_code"
            , "jrn_def_pj_pref"=>"jrn_def_pj_pref"
            , "jrn_def_bank"=>"jrn_def_bank"
            , "jrn_def_num_op"=>"jrn_def_num_op"
            , "jrn_def_description"=>"jrn_def_description"
            , "jrn_enable"=>"jrn_enable"
            , "currency_id"=>"currency_id"
            , "jrn_def_negative_amount"=>"jrn_def_negative_amount"
            , "jrn_def_negative_warning"=>"jrn_def_negative_warning"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "jrn_def_id"=>"numeric"
            , "jrn_def_name"=>"text"
            , "jrn_def_class_deb"=>"text"
            , "jrn_def_class_cred"=>"text"
            , "jrn_def_fiche_deb"=>"text"
            , "jrn_def_fiche_cred"=>"text"
            , "jrn_deb_max_line"=>"numeric"
            , "jrn_cred_max_line"=>"numeric"
            , "jrn_def_ech"=>"boolean"
            , "jrn_def_ech_lib"=>"text"
            , "jrn_def_type"=>"text"
            , "jrn_def_code"=>"text"
            , "jrn_def_pj_pref"=>"text"
            , "jrn_def_bank"=>"numeric"
            , "jrn_def_num_op"=>"numeric"
            , "jrn_def_description"=>"text"
            , "jrn_enable"=>"numeric"
            , "currency_id"=>"numeric"
            , "jrn_def_negative_amount"=>"text"
            ,"jrn_def_negative_warning"=>"text"
            );

        $this->default=array(
            "jrn_def_id"=>"auto");

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
