<?php
/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


/**
 * class_op_predef_sql.php
 *
 *@file
 *@brief abstract of the table public.op_predef */

/**
 *@class Op_Predef_SQL
 *@brief ORM abstract of the table public.op_predef */
 

class Op_predef_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn,$p_id=-1)
    {
        $this->table = "public.op_predef";
        $this->primary_key = "od_id";
        /*
         * List of columns
         */
        $this->name=array(
            "od_id"=>"od_id"
        ,"jrn_def_id"=>"jrn_def_id"
        ,"od_name"=>"od_name"
        ,"od_item"=>"od_item"
        ,"od_jrn_type"=>"od_jrn_type"
        ,"od_direct"=>"od_direct"
        ,"od_description"=>"od_description"
        );
        /*
         * Type of columns
         */
        $this->type = array(
            "od_id"=>"numeric"
        ,"jrn_def_id"=>"numeric"
        ,"od_name"=>"text"
        ,"od_item"=>"numeric"
        ,"od_jrn_type"=>"text"
        ,"od_direct"=>"boolean"
        ,"od_description"=>"text"
        );


        $this->default = array(
            "od_id" => "auto"
        );

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn,$p_id);
    }


}