<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE . '/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE . '/class/database.class.php';

/**
 * @file
 * @brief abstract of the table public.otp_send_secret
 */

/**
 * @class Otp_Send_Secret_SQL
 * @brief abstract of the table public.otp_send_secret
 */
class Otp_Send_Secret_SQL extends \Table_Data_SQL {

    function __construct(Database $p_cn, $p_id = -1) {
        $this->table = "public.otp_send_secret";
        $this->primary_key = "os_id";
        /*
         * List of columns
         */
        $this->name = array(
            "os_id" => "os_id"
            , "os_timestamp" => "os_timestamp"
            , "os_request" => "os_request"
            , "use_id" => "use_id"
            , 'os_valid_time'=>'os_valid_time'
            ,'os_code'=>'os_code'
        );

        /*
         * Type of columns
         */
        $this->type = array(
            "os_id" => "numeric"
            , "os_timestamp" => "date"
            , "os_request" => "text"
            , "use_id" => "numeric"
            , 'os_valid_time'=>'date'
            ,'os_code'=>'text'
        );

        $this->default = array("os_id" => "auto", "os_timestamp" => "auto");

        $this->date_format = "DD.MM.YYYY HH24:MI:SS";
        parent::__construct($p_cn, $p_id);
    }
}
