<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * @file
 * @brief abstract of the table public.payment_method 
 */

/**
 * @brief abstract of the table public.payment_method 
 */
class Payment_method_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.payment_method";
        $this->primary_key="mp_id";
        /*
         * List of columns
         */
        $this->name=array(
            "mp_id"=>"mp_id"
            , "mp_lib"=>"mp_lib"
            , "mp_jrn_def_id"=>"mp_jrn_def_id"
            , "mp_fd_id"=>"mp_fd_id"
            , "mp_qcode"=>"mp_qcode"
            , "jrn_def_id"=>"jrn_def_id"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "mp_id"=>"numeric"
            , "mp_lib"=>"text"
            , "mp_jrn_def_id"=>"numeric"
            , "mp_fd_id"=>"numeric"
            , "mp_qcode"=>"text"
            , "jrn_def_id"=>"numeric"
        );


        $this->default=array(
            "mp_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
