<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE.'/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE.'/class/database.class.php';

/**
 * class_profile_mobile_sql.php
 *
 * @file
 * @brief abstract of the table public.profile_mobile */

/**
 * @class Profile_Mobile_SQL
 * @brief ORM abstract of the table public.profile_mobile 
 */

class Profile_Mobile_SQL extends \Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.profile_mobile";
        $this->primary_key="pmo_id";
        /*
         * List of columns
         */
        $this->name=array(
            "pmo_id"=>"pmo_id"
            , "me_code"=>"me_code"
            , "pmo_order"=>"pmo_order"
            , "p_id"=>"p_id"
            , "pmo_default"=>"pmo_default"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "pmo_id"=>"numeric"
            , "me_code"=>"text"
            , "pmo_order"=>"numeric"
            , "p_id"=>"numeric"
            , "pmo_default"=>"text"
        );

        $this->default=array(
            "pmo_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
