<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE . '/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE . '/class/database.class.php';


/**
 * class_quant_purchase_sql.php
 *
 * @file
 * @brief ORM of the table public.quant_purchase
 *
 */

/**
 * @class Quant_Purchase_SQL
 * @brief ORM of the table public.quant_purchase
 */
class Quant_Purchase_SQL extends \Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id = -1)
    {
        $this->table = "public.quant_purchase";
        $this->primary_key = "qp_id";
        /*
         * List of columns
         */
        $this->name = array(
            "qp_id" => "qp_id"
        , "qp_internal" => "qp_internal"
        , "j_id" => "j_id"
        , "qp_fiche" => "qp_fiche"
        , "qp_quantite" => "qp_quantite"
        , "qp_price" => "qp_price"
        , "qp_vat" => "qp_vat"
        , "qp_vat_code" => "qp_vat_code"
        , "qp_nd_amount" => "qp_nd_amount"
        , "qp_nd_tva" => "qp_nd_tva"
        , "qp_nd_tva_recup" => "qp_nd_tva_recup"
        , "qp_supplier" => "qp_supplier"
        , "qp_valid" => "qp_valid"
        , "qp_dep_priv" => "qp_dep_priv"
        , "qp_vat_sided" => "qp_vat_sided"
        , "qp_unit" => "qp_unit"
        );
        /*
         * Type of columns
         */
        $this->type = array(
            "qp_id" => "numeric"
        , "qp_internal" => "text"
        , "j_id" => "numeric"
        , "qp_fiche" => "numeric"
        , "qp_quantite" => "numeric"
        , "qp_price" => "numeric"
        , "qp_vat" => "numeric"
        , "qp_vat_code" => "numeric"
        , "qp_nd_amount" => "numeric"
        , "qp_nd_tva" => "numeric"
        , "qp_nd_tva_recup" => "numeric"
        , "qp_supplier" => "numeric"
        , "qp_valid" => "text"
        , "qp_dep_priv" => "numeric"
        , "qp_vat_sided" => "numeric"
        , "qp_unit" => "numeric"
        );


        $this->default = array(
            "qp_id" => "auto"
        );

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }


}