<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE . '/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE . '/class/database.class.php';


/**
 * class_quant_sold_sql.php
 *
 * @file
 * @brief ORM of the table public.quant_sold
 */

/**
 * @class Quant_Sold_SQL
 * @brief ORM of the table public.quant_sold
 */
class Quant_Sold_SQL extends \Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id = -1)
    {
        $this->table = "public.quant_sold";
        $this->primary_key = "qs_id";
        /*
         * List of columns
         */
        $this->name = array(
            "qs_id" => "qs_id"
        , "qs_internal" => "qs_internal"
        , "qs_fiche" => "qs_fiche"
        , "qs_quantite" => "qs_quantite"
        , "qs_price" => "qs_price"
        , "qs_vat" => "qs_vat"
        , "qs_vat_code" => "qs_vat_code"
        , "qs_client" => "qs_client"
        , "qs_valid" => "qs_valid"
        , "j_id" => "j_id"
        , "qs_vat_sided" => "qs_vat_sided"
        , "qs_unit" => "qs_unit"
        );
        /*
         * Type of columns
         */
        $this->type = array(
            "qs_id" => "numeric"
        , "qs_internal" => "text"
        , "qs_fiche" => "numeric"
        , "qs_quantite" => "numeric"
        , "qs_price" => "numeric"
        , "qs_vat" => "numeric"
        , "qs_vat_code" => "numeric"
        , "qs_client" => "numeric"
        , "qs_valid" => "text"
        , "j_id" => "numeric"
        , "qs_vat_sided" => "numeric"
        , "qs_unit" => "numeric"
        );


        $this->default = array(
            "qs_id" => "auto"
        );

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }


}