<?php

/**
 * Autogenerated file
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
require_once NOALYSS_INCLUDE . '/lib/data_sql.class.php';
require_once NOALYSS_INCLUDE . '/class/database.class.php';


/**
 * class_quant_fin_sql.php
 *
 * @file
 * @brief ORM of the table public.quant_fin
 */

/**
 * class_quant_fin_sql.php
 *
 * @class Quant_Fin_SQL
 * @brief ORM of the table public.quant_fin
 */
class Quant_Fin_SQL extends \Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id = -1)
    {
        $this->table = "public.quant_fin";
        $this->primary_key = "qf_id";
        /*
         * List of columns
         */
        $this->name = array(
            "qf_id" => "qf_id"
        , "qf_bank" => "qf_bank"
        , "jr_id" => "jr_id"
        , "qf_other" => "qf_other"
        , "qf_amount" => "qf_amount"
        , "j_id" => "j_id"
        );
        /*
         * Type of columns
         */
        $this->type = array(
            "qf_id" => "numeric"
        , "qf_bank" => "numeric"
        , "jr_id" => "numeric"
        , "qf_other" => "numeric"
        , "qf_amount" => "numeric"
        , "j_id" => "numeric"
        );


        $this->default = array(
            "qf_id" => "auto"
        );

        $this->date_format = "DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }


}