<?php

/**
 * Autogenerated file 
 *   This file is part of NOALYSS.
 *
 *   NOALYSS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   NOALYSS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NOALYSS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * class_tva_rate_sql.php
 *
 * @file
 * @brief abstract of the table public.tva_rate
 * 
 */

/**
 * @class Tva_rate_SQL
 * @brief abstract of the table public.tva_rate
 */
class Tva_rate_SQL extends Table_Data_SQL
{

    function __construct(DatabaseCore $p_cn, $p_id=-1)
    {
        $this->table="public.tva_rate";
        $this->primary_key="tva_id";
        /*
         * List of columns
         */
        $this->name=array(
            "tva_id"=>"tva_id"
            , "tva_label"=>"tva_label"
            , "tva_rate"=>"tva_rate"
            , "tva_comment"=>"tva_comment"
            , "tva_poste"=>"tva_poste"
            , "tva_both_side"=>"tva_both_side"
            ,"tva_payment_purchase"=>"tva_payment_purchase"
            ,"tva_payment_sale"=>"tva_payment_sale"
        );
        /*
         * Type of columns
         */
        $this->type=array(
            "tva_id"=>"numeric"
            , "tva_label"=>"text"
            , "tva_rate"=>"numeric"
            , "tva_comment"=>"text"
            , "tva_poste"=>"text"
            , "tva_both_side"=>"numeric"
            ,"tva_payment_purchase"=>"text"
            ,"tva_payment_sale"=>"text"

        );


        $this->default=array(
            "tva_id"=>"auto"
        );

        $this->date_format="DD.MM.YYYY";
        parent::__construct($p_cn, $p_id);
    }

}
