<?php
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-11 at 15:41:40.
 */
class DatabaseTest extends TestCase

{

    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Database(DOSSIER);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }
    public function testDatabase()
    {
        $this->assertEquals(DBVERSION,$this->object->get_version(),"check Version");
        
    }

    

}
