<?php
use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-11 at 15:39:21.
 */
class DossierTest extends TestCase
{

    /**
     * @var Dossier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object=new Dossier(DOSSIER);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Dossier::synchro_admin
     */
    public function testSynchro_admin()
    {
       Dossier::synchro_admin(DOSSIER);
    }

}
