<?php
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-07 at 23:05:36.
 * @backupGlobals enabled
 */
require 'global.php';
class FicheTest extends TestCase
{

    /**
     * @var Fiche
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Fiche::cmp_name
     * @todo   Implement testCmp_name().
     */
    public function testCmp_name()
    {
       
    }

    /**
     * @covers Fiche::get_bk_account
     * @todo   Implement testGet_bk_account().
     */
    public function testGet_bk_account()
    {
     include 'global.php';
     $this->object=new Fiche($g_connection);
     $result=$this->object->get_bk_account();
     $this->assertEquals(gettype($result),'array');
     $count = count($result);
     $this->assertGreaterThan(0,$count);
     
    }

    /**
     * @covers Fiche::get_row
     */
    public function testGet_row()
    {
       $this->assertTrue(is_array($this->object->get_row(235,238)));
       
    }

}
