alter table attr_min add ad_default_order int;

update attr_min set ad_default_order = a1.ad_default_order from attr_def a1 where a1.ad_id = attr_min.ad_id;


select replace_menu_code('CFGACC','C0PST');
select replace_menu_code('CFGDOC','C0DOC');
select replace_menu_code('CFGSEC','C0SEC');
select replace_menu_code('CFGPCMN','C0PCMN');
select replace_menu_code('CFGPRO','C0PROFL');
select replace_menu_code('CFGLED','C0JRN');
select replace_menu_code('CFGDOCST','C1DOC');
select replace_menu_code('CFGDEFMENU','C0MENU');
select replace_menu_code('CFGPAY','C0PAY');
select replace_menu_code('CFGCURRENCY','C0DEV');
select replace_menu_code('CFGACTION','C0ACT');
select replace_menu_code('CFGOPT1','C0OPT1');
select replace_menu_code('CFGSTOCK','C0STOCK');
select replace_menu_code('CFGPLUGIN','C0PLG');
select replace_menu_code('CFGTAG','C0TAG');

update menu_ref set me_description ='Configuration des extensions' where me_code='C0PLG';
update menu_ref set me_description ='Clef de répartition pour la comptabilité analytique' where me_code='ANCKEY';

--- widget pour DASHBOARD
drop table dashboard_widget;
drop table if exists user_widget;
drop table if exists  user_widger;
drop table if exists widget_dashboard;

create table widget_dashboard(
                                 wd_id int primary key generated by default as identity,
                                 wd_code text not null,
                                 wd_description text not null,
                                 wp_parameter int not null default 0
);



create table  user_widget(
                             uw_id int primary key generated by default as identity,
                             use_login text not null,
                             dashboard_widget_id int not null references widget_dashboard(wd_id) on update cascade on delete cascade,
                             uw_parameter text ,
                             uw_order int
);

ALTER TABLE public.widget_dashboard RENAME COLUMN wp_parameter TO wd_parameter;
ALTER TABLE public.widget_dashboard ADD CONSTRAINT widget_dashboard_unique UNIQUE (wd_code);

INSERT INTO public.widget_dashboard (wd_id,wd_code,wd_description,wd_parameter,wd_name) VALUES
                                                                                      (1,'agenda','Présentation d''un calendrier avec les dates de rappel des événements',0,'Agenda'),
                                                                                      (2,'todo_list','Liste de choses à faire , de petites notes',0,'Pense-Bête'),
                                                                                      (3,'coming_event','Rappel pour des actions pour  aujourd''hui ou en retard',0,'Actions'),
                                                                                      (4,'last_operation','Affichage des dernières opérations comptables saisies',0,'Comptabilité'),
                                                                                      (5,'last_event','Affiche les derniers actions de suivi',0,'Suivi'),
                                                                                      (6,'mini_report','Affiche des rapports de comptabilité',1,'Rapport');


INSERT INTO public.user_widget (use_login,dashboard_widget_id,uw_parameter,uw_order)
    VALUES
         ('admin',1,NULL,10),
         ('admin',3,NULL,30),
         ('admin',4,NULL,40),
         ('admin',5,NULL,50),
         ('admin',2,NULL,45);

alter table  public.widget_dashboard add wd_name text;
ALTER TABLE public.widget_dashboard ALTER COLUMN wd_name SET NOT NULL;

ALTER TABLE public.widget_dashboard ALTER COLUMN wd_name SET NOT NULL;
COMMENT ON COLUMN public.widget_dashboard.wd_name IS 'Name';
COMMENT ON COLUMN public.widget_dashboard.wd_id IS 'PK';
COMMENT ON COLUMN public.widget_dashboard.wd_code IS 'Code';
COMMENT ON COLUMN public.widget_dashboard.wd_description IS 'Description';
COMMENT ON COLUMN public.widget_dashboard.wd_parameter IS 'presence of  there is a parameter';

update menu_ref set me_menu = me_menu ||' &#128100;' where me_code='PREFERENCE';
update menu_ref set me_menu = 'Impression &#x1F4CA;' where me_code='PRINT';
update menu_ref set me_menu = me_menu || '&#x1F4CA;' where me_code='RAPAV';
update menu_ref set me_menu = me_menu ||' &#x1F4C7;' where me_code='CARD';
update menu_ref set me_menu  = 'Favori &#x2728;' where me_code='BOOKMARK';
